### ISSUE TITLE
Feature: Add load * distance class

### ISSUE THREAD

**Issue by jhok2013** [jhok2013/processCalculator#2]
# Description
Add a feature that can represent a load * distance problem and can contain methods to solve it.

# Task List

- [ ] Create class for load * distance
- [ ] Add getter or setter methods
- [ ] Add defaults for attributes
- [ ] Make way to compare multiple processes to each other.
