### ISSUE TITLE
Add type and input validation to all classes and functions.

### ISSUE THREAD

**Issue by jhok2013** [jhok2013/processCalculator#3]
# Description
The classes don't have any type validation or unit tests to validate that the code works. That needs to change.

# Task List

- [x] Add type validation
- [x] Update existing unit tests
- [ ] Add negative testing against current type validation
- [ ] Ensure everything is PEP standard ( doclines, etc)
