### ISSUE TITLE
Create ComplexBreakEven class

### ISSUE THREAD

**Issue by jhok2013** [jhok2013/processCalculator#4]
# Description
The SimpleBreakEven class is sufficient for quick and easy stuff but not for more complex comparisons of greater than two processes. I need to find a way to make that possible.

# Task List

- [ ] Make ComplexBreakEven class
- [ ] Make costProcess() class
- [ ] Add testing 
- [ ] Add doclines
- [ ] Update *README.md*
